# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Valinor
repo_url: https://github.com/CuyZ/Valinor
repo_name: CuyZ/Valinor
edit_uri: edit/master/docs/
docs_dir: pages

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CuyZ
    - icon: fontawesome/solid/globe
      link: https://cuyz.io

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/pine-tree
  features:
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/links.md
  - pymdownx.superfences
  - admonition

nav:
  - Introduction: index.md
  - Getting Started: getting-started
  - Credits: credits
  - Usage:
      - Validation: validation
      - Message customization: message-customization
      - Source: source
  - Mapping:
      - Construction strategy: mapping/construction-strategy
      - Inferring interfaces: mapping/inferring-interfaces
      - Handled types: mapping/handled-types
  - Other:
      - Performance & caching: other/performance-and-cache
      - Static analysis: other/static-analysis
