name: Publish docs via GitHub Pages
on:
  release:
    types:
      - published

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Version format check
        run: if [ "${{ steps.get_version.outputs.is-semver }}" = "false" ]; then exit 1; fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Set up git author
        uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy docs
        run: mike deploy --push ${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} --config-file docs/mkdocs.yml

      - name: Set default version
        run: mike set-default --push ${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} --config-file docs/mkdocs.yml
