name: Publish docs via GitHub Pages
on:
  release:
    types:
      - published

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive #todo

      - name: Find version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Version format check
        run: if [ "${{ steps.get_version.outputs.is-semver }}" = "false" ]; then exit 1; fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Set up git author
        uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy docs
        run: |
          git fetch origin gh-pages --verbose
          mike deploy --push --rebase ${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} --config-file docs/mkdocs.yml

      - name: Find latest release
        id: latest
        uses: pozetroninc/github-action-get-latest-release@v0.6.0
        with:
          repository: ${{ github.repository }}
          excludes: draft

      - name: Set default version
        run: |
          if [ "${{ steps.keydb.outputs.release }}" = "${{ steps.get_version.outputs.version-without-v }}" ]
          then
            mike set-default --push --rebase ${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} --config-file docs/mkdocs.yml
          fi
