name: Publish docs
on:
  release:
    types:
      - published

jobs:
  check:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}
      version: ${{ steps.check.outputs.version }}
      tag: ${{ steps.check.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Version format check
        id: check
        run: |
          if [ "${{ steps.get_version.outputs.is-semver }}" == "true" ]
          then
            echo "::set-output name=status::ok"
            echo "::set-output name=version::${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}"
            echo "::set-output name=tag::${{ steps.get_version.outputs.version-without-v }}"
          fi

  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'ok'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Set up git author
        uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Find latest release
        id: latest
        uses: pozetroninc/github-action-get-latest-release@v0.6.0
        with:
          repository: ${{ github.repository }}
          excludes: draft

      - name: Deploy docs
        run: |
          git fetch origin gh-pages --verbose
          
          git remote add doc git@github.com:Mopolo/Valinor-docs-test.git
          
          if [ "${{ steps.latest.outputs.release }}" = "${{ needs.check.outputs.tag }}" ]
          then
            mike deploy ${{ needs.check.outputs.version }} latest --config-file docs/mkdocs.yml --update-aliases --push --rebase --remote doc
          else
            mike deploy ${{ needs.check.outputs.version }} --config-file docs/mkdocs.yml --push --rebase --remote doc
          fi
